### ISSUE TITLE
index 추가 건의

### ISSUE THREAD

**Issue by Gaeduck-0908** [Sungil-SoftWare-Study/Sungil-SoftWare-Study.github.io#1]
[Readme.md 변경사항 바로가기](https://github.com/Sungil-SoftWare-Study/Sungil-SoftWare-Study/commit/29c0ca1048106b88b9ec3b085377e75374b61bd7)
> 변경된 부분
```
<h3> 활동 이력은 재학 당시 활동만 기재합니다. </h3>
```

스터디 Github 메인 페이지에 걸려있는 Readme.md 변경함에 따라 사이트 index 에 내용도 변경하는게 어떨까 싶습니다.

**Comment by saintlee83** [comment]
오늘 내로 수정 하겠습니다.
